# Generated by Django 4.0.6 on 2022-10-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(max_length=100)),
                ('chead0', models.CharField(max_length=10000)),
                ('head1', models.CharField(max_length=100)),
                ('chead1', models.CharField(max_length=10000)),
                ('head2', models.CharField(max_length=100)),
                ('chead2', models.CharField(max_length=10000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
