# Generated by Django 4.0.6 on 2022-10-08 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
