# Generated by Django 4.0.6 on 2022-09-29 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 29, 15, 39, 14, 130289, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
